### ISSUE TITLE
Complete 2.0.0-2.0.3 documentation

### ISSUE THREAD

**Issue by Depal1** [PlayCover/PlayBook#53]
This is a list of things that have been identified so far as missing in PlayBook.

## page updates:
* download_playcover.md
    - [x] Additional Homebrew cask information (nightlies and prerelease)
* miscellaneous.md
    - [x] Update the screenshot for misc settings https://github.com/PlayCover/PlayCover/pull/663
    - [x] Talk about PlayTools removal and injection, possible consequences, etc
* alt_xcode_cli_install.md
    - [x] Xcode CLT troubleshooting (to be adapted from the server’s faq)
* using_making_keymaps.md
    - [x] Controller keymap support
    - [x] Mention what keys can be mapped or not (option key, F keys, numeric keyboard extra keys, middle button, scroll)

## new pages to add:
- [x] account (store,switch,delete)
- [x] clear app data, clear app preferences, uninstall app (and what the uninstall popup checkboxes do)
- [x] PlayCover settings menu (info on app deletion settings [list deleted directories], including prune)
- [x] IPA LIBRARY info (what it looks like, what it does, how to use it)
- [x] IPA Library: how to make a source
- [x] probably a page on explaining what to do when a game (like genshin) updates (and troubleshooting the problems that may occur, other potential issues)
- [x] PlayCover utilities and related projects (IPA Source Tool, PCTT, PlayCover CLI, PlayCover Raycast extension)
- [x] Info on blocked games and malicious apps (explanation and list)

## other pending changes:
- [x] Document Sideloadly export
- [x] How to configure entitlements and Jailbreak bypass (to be adapted from @ohaiibuzzle‘s notes) https://github.com/PlayCover/PlayBook/pull/61
- [x] Mention photos saved through apps are stored in your Photos Library.
- [x] Document screen rotation and the fact that it is only officially intended to fix rotation issues during the execution of the app, and that the rotation status is not saved.
- [x] Mention the case of some apps running with SIP enabled in 'fresh' Xcode builds, due to access to otherwise inaccesible frameworks such as OpenGL ES.
- [x] Mention PlayCover has to be in the Applications folder in order to work correctly.
- [x] Mention that in-app purchases won’t work at all.
- [x] More detailed documentation on configuring Custom Discord Activity
- [x] Mention explicitly the possibility to have multiple accounts in the account manager
- [x] Research behaviour of legitimately signed apps inside PlayCover's container. (@Depal1 )

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
maybe also a good idea to improve the readme instructions on how to contribute properly to playbook

**Comment by Depal1** [comment]
> maybe also a good idea to improve the readme instructions on how to contribute properly to playbook

Is this better?
https://github.com/PlayCover/PlayBook/commit/9e84bb51e22deaef7beb932c58f31e5602e9e206

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
i was thinking even more detailed if possible, imagine like... your grandma wants to help contribute to the docs but has no idea how to do so properly

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
i can take care of these ones since they're more user facing and dont require deeper knowledge of playcover code

- [x] Update the screenshot for misc settings https://github.com/PlayCover/PlayBook/pull/54
- [x] Talk about PlayTools removal and injection, possible consequences, etc https://github.com/PlayCover/PlayBook/pull/55 
- [x] Mention what keys can be mapped or not (option key, F keys, numeric keyboard extra keys, middle button, scroll) https://github.com/PlayCover/PlayBook/pull/55
- [x] account (store,switch,delete) https://github.com/PlayCover/PlayBook/pull/57
- [x] clear app data, clear app preferences, uninstall app (and what the uninstall popup checkboxes do) - gonna need some help with these since idk what some of them actually do and their impacts https://github.com/PlayCover/PlayBook/pull/63
- [x] PlayCover settings menu (info on app deletion settings [list deleted directories], including prune) - might need some help with these too https://github.com/PlayCover/PlayBook/pull/63
- [x] IPA LIBRARY info (what it looks like, what it does, how to use it) https://github.com/PlayCover/PlayBook/pull/63
- [x] probably a page on explaining what to do when a game (like genshin) updates (and troubleshooting the problems that may occur, other potential issues) -prob have to also elaborate the app duplicating issue is due to migrating from older version (as u mentioned b4) https://github.com/PlayCover/PlayBook/pull/62
- [x] Mention photos saved through apps are stored in your Photos Library. (cant add pics for this one cuz photo library broke) https://github.com/PlayCover/PlayBook/pull/63
- [x] Document screen rotation and the fact that it is only officially intended to fix rotation issues during the execution of the app, and that the rotation status is not saved. https://github.com/PlayCover/PlayBook/pull/55 
- [x]  Mention PlayCover has to be in the Applications folder in order to work correctly.
- [x]  Mention that in-app purchases won’t work at all.
- [x] page explaining playcover settings https://github.com/PlayCover/PlayBook/pull/63
